pluginManagement {
    repositories {
        google()        
        mavenCentral()  
        gradlePluginPortal() 
    }
}

// It's also good practice to define dependency resolution management here
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

include ':src'